/// Flutter icons TheProductsbook
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TheProductsbook
///      fonts:
///       - asset: fonts/TheProductsbook.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class TheProductsbookIcons {
  TheProductsbookIcons._();

  static const String _kFontFam = 'TheProductsbook';

  static const IconData book = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData globe = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData archer = IconData(0xe90d, fontFamily: _kFontFam);
  static const IconData broadsword = IconData(0xe946, fontFamily: _kFontFam);
  static const IconData user_circle = IconData(0xf2bd, fontFamily: _kFontFam);
  static const IconData theater_masks = IconData(0xf630, fontFamily: _kFontFam);
}
